apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: php-cm
    app.kubernetes.io/component: php-cm
    app.kubernetes.io/instance: php-cm
  name: php-cm
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deployment: php-cm
  sessionAffinity: None
  type: ClusterIP
