kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: phpdemo
spec:
  destination:
    namespace: phpdemo
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/template/spec/containers
  project: phpdemo
  source:
    path: manifests/base
    repoURL: https://github.com/masauve/php-json-reader-app.git
    targetRevision: main
